# Generated by Django 2.1.11 on 2019-08-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivel',
            name='is_winner',
            field=models.BooleanField(default=False, verbose_name='is lottery winner'),
        ),
        migrations.AddField(
            model_name='fivel',
            name='nth',
            field=models.CharField(default=375, max_length=5, verbose_name='nth of lottery'),
        ),
        migrations.AddField(
            model_name='fivel',
            name='prize_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='winning prize detail'),
        ),
        migrations.AddField(
            model_name='onel',
            name='is_winner',
            field=models.BooleanField(default=False, verbose_name='is lottery winner'),
        ),
        migrations.AddField(
            model_name='onel',
            name='nth',
            field=models.CharField(default=375, max_length=5, verbose_name='nth of lottery'),
        ),
        migrations.AddField(
            model_name='onel',
            name='prize_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='winning prize detail'),
        ),
        migrations.AddField(
            model_name='twol',
            name='is_winner',
            field=models.BooleanField(default=False, verbose_name='is lottery winner'),
        ),
        migrations.AddField(
            model_name='twol',
            name='nth',
            field=models.CharField(default=375, max_length=5, verbose_name='nth of lottery'),
        ),
        migrations.AddField(
            model_name='twol',
            name='prize_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='winning prize detail'),
        ),
        migrations.AlterField(
            model_name='fivel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='onel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='twol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
